#!/bin/bash
: '
Shell script that runs Python code.
The Python code will be saved in the environment variable $PYCODE
The script first checks if the env variable is set
It then checks if the python code exists.
'

if [ -z "$PYCODE" ]; then
    echo "Error: the environment variable PYCODE is not set."
    exit 1
fi

python3 <<< "$PYCODE"